// skillgen scaffold — generates a complete Agent Skill project from a template

import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { loadTemplate } from './templates.js';
import { render } from './render.js';
import { validateName, TYPES, LANGS } from './validate.js';

export const EXAMPLE_SCRIPT = `#!/usr/bin/env node
/**
 * {{name}} — example script
 * Replace this file with real logic, then reference it from SKILL.md.
 * 将本文件替换为真实逻辑，并在 SKILL.md 中引用。
 *
 * Usage / 用法: node scripts/example.js <args...>
 */
const input = process.argv.slice(2);
console.log('[{{name}}] example script ran with:', input);
`;

export const GENERATED_README = `# {{name_title}}

{{description}}

> Generated by skillgen · https://github.com/qyp1a/skillgen

## Install / 安装

Copy this folder into your agent's skills directory, e.g. \`~/.codex/skills/\`, \`~/.claude/skills/\`, or run \`codex install ./{{name}}\`.
将本目录复制到你的 Agent skills 目录（如 \`~/.codex/skills/\`、\`~/.claude/skills/\`），或执行 \`codex install ./{{name}}\`。

## Structure / 结构

- \`SKILL.md\` — skill definition (main entry) / 技能定义（主入口）
- \`scripts/\` — executable scripts / 可执行脚本
- \`assets/\` — reference assets / 参考资源

## License

MIT © {{author}}
`;

export const LICENSE_MIT = `MIT License

Copyright (c) {{year}} {{author}}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;

function titleCase(name) {
  return name
    .split('-')
    .map((s) => (s ? s.charAt(0).toUpperCase() + s.slice(1) : s))
    .join(' ');
}

function cleanDescription(desc) {
  return (desc || '').replace(/[\r\n]+/g, ' ').replace(/"/g, "'").trim();
}

/**
 * Generate a skill project into ./<name> of the current working directory.
 * @param {object} opts
 * @param {string} opts.name      skill name (e.g. my-skill)
 * @param {string} [opts.desc]    one-line description
 * @param {string} opts.type      template type: basic | cli | workflow | mcp
 * @param {string} opts.lang      template language: zh | en | both
 * @param {string} [opts.author]  author name for LICENSE/README
 * @param {boolean} [opts.force]  overwrite existing directory
 * @returns {Promise<{dir: string, files: string[]}>}
 */
export async function scaffold(opts) {
  const { name, type, lang } = opts;
  if (!validateName(name)) throw new Error(`Invalid name: ${name}`);
  if (!TYPES.includes(type)) throw new Error(`Invalid type: ${type}`);
  if (!LANGS.includes(lang)) throw new Error(`Invalid lang: ${lang}`);

  const dir = join(process.cwd(), name);
  if (!opts.force && existsSync(dir)) {
    throw new Error(`Target directory already exists: ${dir} (use --force to overwrite)`);
  }

  const vars = {
    name,
    name_title: titleCase(name),
    description: cleanDescription(opts.desc || `A ${type} skill for ${name}.`),
    author: opts.author || 'Your Name',
    year: String(new Date().getFullYear())
  };

  const files = {
    'SKILL.md': render(loadTemplate(type, lang), vars),
    'scripts/example.js': render(EXAMPLE_SCRIPT, vars),
    'assets/.gitkeep': '',
    'README.md': render(GENERATED_README, vars),
    'LICENSE': render(LICENSE_MIT, vars)
  };

  for (const [rel, content] of Object.entries(files)) {
    const full = join(dir, rel);
    await mkdir(join(full, '..'), { recursive: true });
    await writeFile(full, content, 'utf8');
  }

  return { dir, files: Object.keys(files) };
}
